### ISSUE TITLE
onLoginFinished never is fired

### ISSUE THREAD

**Issue by CharlyJazz** [facebook/react-native-fbsdk#687] opened 2019-12-28 01:22 UTC
``` jsx
import React, {Component} from 'react';
import {View} from 'react-native';
import {LoginButton, AccessToken} from 'react-native-fbsdk';
import get_user_by_email from '../services/get_user_by_email';

export default class FBLoginButton extends Component {
  render() {
    return (
      <View
        style={{
          justifyContent: 'center',
          height: 80,
          alignItems: 'center',
        }}>
        <LoginButton
          publishPermissions={['email']}
          onLoginFinished={(error, result) => {
            if (error) {
              console.log('login has error: ' + result.error);
            } else if (result.isCancelled) {
              console.log('login is cancelled.');
            } else {
              AccessToken.getCurrentAccessToken().then(data => {
                console.log(data.accessToken.toString());
              });
            }
          }}
          onLogoutFinished={() => alert('User logged out')}
        />
      </View>
    );
  }
}

module.exports = FBLoginButton;

```

This code was copypasted from the README. And not work. BUT onLogoutFinished its called perfectly.

### Env

```
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-fbsdk": "^1.1.1"
```

**Comment by tsirolnik** [comment] 2019-12-31 12:57
Having the same issue - 

```js
<LoginButton
              permissions={["email"]}
              onLoginFinished={() => Alert.alert("User logged in")}
              onLogoutFinished={() => Alert.alert("User logged out")} />

```
"react-native-fbsdk": "^1.1.1"
react: 16.8.6 => 16.8.6 
 react-native: 0.60.5 => 0.60.5

onLogoutFinished is called, but not onLoginFinished

**Comment by edwardhsueh** [comment] 2020-01-09 13:39
Hi, I found a strange behavior. The onLoginFinished is issued in release mode(react-native run-android --variant=release), but NOT in debug mode.

**Comment by gmertk** [comment] 2020-02-24 18:20
I was not able to repro this on Android or iOS with the following versions. Facebook app wasn't installed.

```
  {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-fbsdk": "^1.1.2"
  }
```

**Comment by stefandima** [comment] 2020-03-10 22:11
This reproduce on android exactly with 
```
{
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-fbsdk": "^1.1.2"
  }
```
To reproduce this, you must reload once the application.
If i delete all the data saved by the application, onLoginFinished is called.
If i shake the device, and chose reload, when i try to login onLoginFinished is not called anymore. The login is done with success. Button changes from "Continue with facebok" into "Disconnect". If i reload again the app, because i check in constructor if i'm logged in, i will be logged in.
Problem is that at login, only the button is changed, not the rest of the screen, because my state doesn't change anymore via onLoginFinished.
I tried to find if another event is fired, but without success.

**Comment by Harsh-Choudhary-01** [comment] 2020-04-09 18:48
I also have this issue, seems like it's something to do with reloading/debugging the app.

**Comment by samipshah100** [comment] 2020-04-30 11:18
Same issue here in debugging mode. It was called the first time so I assume its because of the data stored in app. It's going to be painful to re build react native everytime I want to debug this. Any other suggestions?

**Comment by stefandima** [comment] 2020-04-30 12:19
As a work around, I don't use reload function of the client. If I want a refresh, I either close the app, remove from recent opened apps, and open again the app, either use the auto refresh option by changing something in the code, and app will refresh to new code.
HTH

**Comment by samipshah100** [comment] 2020-04-30 12:34
Do you mean the live reload?

**Comment by samipshah100** [comment] 2020-04-30 13:25
@stefandima can you please elaborate, because closing app and opening again doesn't work for me.

**Comment by stefandima** [comment] 2020-05-01 07:38
Solution is to rebuild now the application. Install again on the device, and after that never use the reload option directly from application.
If you will need a reload after that, either close the app, remove from memory, and start again (sometime is needed because is loosing connection with the Metro Server), either relay on live reload.
Never:
- shake the phone and choose reload option
- in case of a error displayed on the app, don't press the reload option.
I'm working like that for the last 2 months, and is working fine.

**Comment by Jaffarraza12** [comment] 2020-05-02 09:30
I have done that remove app from device and build again .Issue persist OnLoginFinished never firing.

**Comment by samipshah100** [comment] 2020-05-02 11:19
Gradlew clean and run react native run Android again

**Comment by Jaffarraza12** [comment] 2020-05-07 12:02
I found my problem after going through this.https://github.com/facebook/react-native-fbsdk In my MainActivity class I was using CallbackManager instance locally initiated. After referring to CallbackManager instance of MainApplication class, onLoginFinished functioned triggered!! :)

please refer : https://reactnativecode.com/facebook-login-integration/

**Comment by nastari** [comment] 2020-07-16 18:08
the problem is that it fires once and then creates some cache somewhere and it ignores onLoginFinish, but I need to retest the server's responses. The callback works, but some problem in the memory

**Comment by afouchet** [comment] 2020-07-26 08:45
> I found my problem after going through this.https://github.com/facebook/react-native-fbsdk In my MainActivity class I was using CallbackManager instance locally initiated. After referring to CallbackManager instance of MainApplication class, onLoginFinished functioned triggered!! :)
> 
> please refer : https://reactnativecode.com/facebook-login-integration/

Tried this, did not work for me :-(

**Comment by afouchet** [comment] 2020-07-26 08:57
I have the issue with :
- react-native 0.63.0
- react-native-fbsdk: ^2.0.0

**Closed** 2020-07-30 12:33 UTC

**Comment by afouchet** [comment] 2020-07-30 12:39
@CharlyJazz Can you tell us why you closed the issue ? I still have the problem.
Did you fix it ?

Personnally, I went around it in a dirty way : On the screen with the LoginButton, I asked every 0.1s fbsdk's AccessToken.getCurrentAccessToken
-> if it returns something, I can log my user (because he is logged in).

But I'd rather have an event fired on onLoginFinished ...

**Comment by danieljgp2** [comment] 2020-08-18 17:37
As @Jaffarraza12 said, it seems that the problem is related to the callback manager.

To fix this, just add the following code on your MainApplication.java

On your imports add the following import

`import com.facebook.reactnative.androidsdk.FBSDKPackage;`

And next on your MainApplication class add this.

`  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();
    protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }`

After doing this the onFinishedLogin callback will be called everytime.

**Comment by ZeeshanAhmadKhalil** [comment] 2020-11-09 07:46
I was facing the same problem, the problem was that I didn't enter my **hash key** while enabling Facebook login also I didn't tell my name **Package Name** and **Default Activity Class Name**.

Just make sure you follow all the steps in **Quick Start** after enabling the Facebook login, you might missing something or doing something wrong while following **Quick Start**. 

Like I am still doing now and getting ErrorThe key hash does not match any stored key hashes.
To resolve this error going through [#424](https://github.com/facebook/react-native-fbsdk/issues/424) I am sure I will find a solution :)
