### ISSUE TITLE
react-native 0.10 update > NSNumber

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native-fbsdk#20] opened 2015-08-27 20:24 UTC
Hi,

Since React Native 0.10 update, I'm encoutering a new error:
"Argument 1 (NSNumber) of RCTFBSDKGraphRequestManager.startConnection must not be null"

I'm using fbsdk 0.0.5 and here's the full red box:
![image](https://cloud.githubusercontent.com/assets/12211685/9532185/53bb94c8-4d0a-11e5-99f9-3188b65ba692.png)

Thanks for your help!

**Comment by amccloud** [comment] 2015-08-30 06:40
I'm seeing the same error. Looks like this was added by https://github.com/facebook/react-native/commit/95b9dd3a88043a97a00c09543138284a63072589

I've checked the call-site and connectionId is 0. I've also tried making connectionId start from 1.

**Comment by amccloud** [comment] 2015-08-30 07:36
I completely looked over the other arguments. The issue is the timeout argument must be set now.

**Comment by amccloud** [comment] 2015-08-30 07:44
It appears that the callback also can't be null. Work around is to dispatch your request manually instead of calling `send()` on it.

```javascript
FBSDKGraphRequestManager.batchRequests([profileRequest], function() {}, 60);
```

**Comment by tnguyen42** [comment] 2015-09-01 09:46
Should we wait for a fix or should I manually patch it for the moment? ^^

**Comment by mponizil** [comment] 2015-09-06 06:04
```
FBSDKGraphRequestManager.batchRequests([profileRequest], function() {}, 60);
```
suppresses the red error screen, but still getting `The operation couldn’t be completed` in Chrome debugger. My code:

```
var fetchFriendsRequest = new FBSDKGraphRequest((error, result) => {
  console.log('FBSDKGraphRequest', error, result);
}, '/me/friends?fields=id,name');
```

User has been authenticated and authorized `user_friends` read permissions.

react-native@0.10.1
react-native-fbsdkcore@0.5.0

**Comment by ceditoph** [comment] 2015-09-08 01:50
Doesn't null evaluate to 0?
Where is the connectionID being set?

**Comment by amccloud** [comment] 2015-09-08 01:57
@ceditoph Sorry, connectionID is correct. The issue is the timeout and callback are null.

**Comment by ceditoph** [comment] 2015-09-08 02:35
@amcloud thanks. Where are you assigning profileRequest? I don't see an example.

**Comment by kent10ou** [comment] 2015-09-08 02:36
Hey I'm working with Ceditoph. We're diving into the source code and can't figure out the proper args to pass in

  constructor(callback: (error: ?Object, result: ?Object) => void, graphPath: string, parameters: ?Object, tokenString: ?string, version: ?string, HTTPMethod: ?string) {
    this.callback = callback;
    this.graphPath = graphPath;
    this.parameters = parameters ? parameters : {};
    this.tokenString = tokenString;
    this.version = version;
    this.HTTPMethod = HTTPMethod;
    this.graphErrorRecoveryDisabled = false;
  }

**Comment by amccloud** [comment] 2015-09-08 02:51
@ceditoph it is something like this

```javascript
var profileRequest = new FBSDKGraphRequest((error, result) => {
  if (error) {
    alert('Error making request.');
  } else {
    // Data from request is in result
  }
}, '/me');
```

**Comment by ceditoph** [comment] 2015-09-08 03:00
@amccloud thanks! it's working. I don't really like how they have it set up, but the timeout is a solid workaround! 
@kent10ou and I will keep at it.

**Comment by ceditoph** [comment] 2015-09-08 17:54
@amccloud so we have it working without getting an error, but how do I grab the result of batch running profileRequest?
Can I use a promise, like .then()?

Thanks again

**Comment by ceditoph** [comment] 2015-09-08 18:23
@amccloud nvm. I see the result from the output of fetchFriends

**Comment by nlhkh** [comment] 2015-10-07 07:39
It's been a while, is this considered a bug?

**Comment by valamelkor** [comment] 2015-10-07 08:23
Yep. This is a bug from my point of view. It prevented us from upgrading from 0.9. 

The actual working piece of code: 
```javascript
FBHelper.getFriends = function (success, fail)
{
  var fetchFriends = new FBSDKGraphRequest((error, result) => {
    if (error)
    {
      console.log("->FBHelper.getFriends Error: ", error);
      fail(error);
    }
    else
    {
        success(result);
    }
  }, '/me/friends?fields=id,name,picture' 
  );

  //fetchFriends.start(); //works before 0.10
  FBSDKGraphRequestManager.batchRequests([fetchFriends], function() {}, 60); // works for 0.10 and later
};
```

Thanks @amccloud for workaround, but for me it took some time to figure out how it should be implemented. :)

**Comment by weeweewee** [comment] 2015-10-21 00:52
New to react-native and fbsdk here but after looking at the source code, assigning a timeout to `.start(60)` seemed to be a workaround as well. However, `RCTFBSDKGraphRequestManager` doesn't seem to like the fact that the callback is null.
A simple fix to `GraphRequest.ios.js/start(timeout: number)` where changing the callback from `null` to `function() {}` allows us to use the `start` function once again.
Feels hackish and I'm not too confident about this so I'm leaving it as a comment here.

**Comment by shaneosullivan** [comment] 2015-10-26 01:27
Any movement on getting this properly fixed without hacks?  The SDK is well behind RN in general, working with v0.8.

**Comment by dzhuowen** [comment] 2015-10-28 17:46
This issue has been handled by #44

**Closed by dzhuowen** 2015-10-28 17:46 UTC
